### ISSUE TITLE
Missing protobuf version

### ISSUE THREAD

**Issue by CAFxX** [cloudfoundry/dropsonde-protocol#8]
All the .proto files are missing the following line at the top:

```
syntax = "proto3";
```

> The first line of the file specifies that you're using proto3 syntax: if you don't do this the protocol buffer compiler will assume you are using proto2. This must be the first non-empty, non-comment line of the file.

https://developers.google.com/protocol-buffers/docs/proto3#simple

**Comment by hev** [comment]
We are using proto2 so we don't specify the `syntax`.

**Comment by CAFxX** [comment]
@ahevenor sorry, the comment in the README is very confusing:

"Note: Due to maps not being supported in protoc v2.X, the proto definitions in this repository require protoc v3.0.0 or higher."

protoc 3 emits a warning if the syntax line is missing. In this case the missing line to silence the protoc compiler warnings is 

```
syntax = "proto2";
```
